name: sakecblue
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  easy_localization:
  flutter_signin_button: ^1.0.0
  youtube_player_flutter: ^6.1.0+4
  buttons_tabbar: ^0.1.1+1
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.3
  validators: ^2.0.0+1
  dropdownfield:
  dropdown_search:
  searchable_dropdown:
  autocomplete_textfield:
  cupertino_icons: ^0.1.3
  firebase_core:
  firebase_auth: ^0.16.1
  google_sign_in: ^4.0.14
  flutter_facebook_login: ^3.0.0
  google_maps_flutter: ^0.5.29
  maps_launcher:
  http: ^0.12.0+1
  geocoder: ^0.2.1
  url_launcher: ^5.4.1
  json_serializable: ^3.3.0
  convert: ^2.1.1
  flutter_sparkline: ^0.1.0
  auto_size_text: ^2.1.0
  cloud_firestore: ^0.13.7
  geolocator:
  intl:
  data_connection_checker:
  app_settings:
  google_fonts:
  path_provider: ^1.6.11
  provider: ^4.1.3
  firebase_database: ^3.1.3
  flutter_dialogflow:
  page_transition:
  connectivity:
  flutter_email_sender: ^3.0.1
  fancy_on_boarding: ^1.6.0
  shared_preferences: ^0.5.7+3
  flutter_spinkit: "^4.1.2"
  flutter_blue: any
  device_info: ^0.4.2+4
  flutter_scan_bluetooth: ^1.1.0
#  wifi_info_plugin: ^1.0.6
  flutter_bluetooth_serial: ^0.2.2
#  app_settings: ^4.0.1+1
  location: ^3.0.2
  flare_flutter: ^2.0.3
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  simple_animations: ^1.3.12
  charts_flutter: ^0.9.0
  fl_chart:
  flutter_statusbarcolor: ^0.2.3
  flutter_svg: ^0.17.4
  font_awesome_flutter: ^8.8.1
  fluttertoast: ^4.0.1
  scroll_snap_list: ^0.4.1
  scoped_model: ^1.0.1
  modal_progress_hud: ^0.1.3
  nearby_connections: ^1.0.3
  flutter_local_notifications:
  barcode_scan:
  qr_flutter: ^3.2.0
  hexcolor:
  excel:
  file_picker:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^2.1.0
  pedantic: ^1.9.0
  build_runner: ^1.10.0

flutter_launcher_name:
  name: "SAKECBlue"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Dashboard/
    - images/Precautions/
    - images/nearby/
    - images/TillDash/
    - images/
    - images/admin/
    - images/faq/
    - images/google_logo.png
    - images/app_logo.png
    - images/icback.png
    - images/sakec_logo_sm.png
    - images/sakecbackdrop.jpg
    - assets/districts_of_india_coordinates.json
    - assets/districts_of_india_coordinates_updated.json
    - assets/map_styles.txt
    - assets/covid-bot-xahd-3d906f16c51a.json
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bebas
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: KroaOne
      fonts:
        - asset: fonts/KronaOne-Regular.ttf
          weight: 400
    - family: Helvetica
      fonts:
        - asset: fonts/HelveticaNeue.ttf
    - family: Merri
      fonts:
        - asset: fonts/MerriweatherSans-Light.ttf
    - family: Merrimed
      fonts:
        - asset: fonts/MerriweatherSans-Medium.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
