import 'package:dropdownfield/dropdownfield.dart';
import 'package:flutter/material.dart';
import 'package:sakecblue/Dashboard/dashboard.dart';
import 'package:sakecblue/Nearby/selecting_resources.dart';

import '../page_transition.dart';

class App extends StatefulWidget {
  final String location;

  App({this.location});

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  String city_id;
  List<String> city = [
    'A.R. Nagar',
    'Adat',
    'Adichanallur',
    'Adilabad',
    'Adimali',
    'Adoor',
    'Agali',
    'Agar Malwa',
    'Agartala',
    'Agra',
    'Ahmedabad',
    'Ahmednagar',
    'Aikkaranad',
    'Ajmer',
    'Ajnala',
    'Akalakunnam',
    'Akathethara',
    'Akola',
    'Ala',
    'Alackode',
    'Alagappanagar',
    'Alakkode',
    'Alanallur',
    'Alangad',
    'Alankode',
    'Alapadambu',
    'Alappad',
    'Alappuzha',
    'Alathur',
    'Alayamon',
    'Aligarh',
    'Aliparamba',
    'Alipurduar',
    'Alirajpur',
    'Allahabad',
    'Aloor',
    'Aluva',
    'Alwar',
    'Amarambalam',
    'Ambalappara',
    'Ambalappuzha',
    'Ambalavayal',
    'Amballoor',
    'Ambalppuzha',
    'Amboori',
    'Ampati',
    'Amravati',
    'Amritsar',
    'Anakkara',
    'Anakkayam',
    'Ananganadi',
    'Anchal',
    'Andoorkonam',
    'Angadippuram',
    'Angamaly',
    'Anikad',
    'Anjarakandi',
    'Annamanada',
    'Anthikkad',
    'Anthoor',
    'Anuppur',
    'Arakulam',
    'Arakuzha',
    'Aralam',
    'Aranmula',
    'Arattupuzha',
    'Areacode',
    'Arikkulam',
    'Ariyalur',
    'Arookutty',
    'Aroor',
    'Arpookkara',
    'Aruvappulam',
    'Aryad',
    'Aryankavu',
    'Aryankode',
    'Ashok Nagar',
    'Asifabad',
    'Assamannoor',
    'Athavanad',
    'Athirampuzha',
    'Athiyannoor',
    'Atholi',
    'Attingal',
    'Aurangabad',
    'Avanoor',
    'Avoly',
    'Ayancheri',
    'Ayarkunnam',
    'Ayavana',
    'Ayilur',
    'Aymanam',
    'Ayroor',
    'Ayyampuzha',
    'Ayyankunnu',
    'Ayyappancovil',
    'Azhikode',
    'Azhiyur',
    'Azhoor',
    'Baba Bakala',
    'Baghmara',
    'Baghpat',
    'Baksa',
    'Balaghat',
    'Balod',
    'Baloda Bazar',
    'Balrampur',
    'Balussery',
    'Bambolim',
    'Bangalore',
    'Banswara',
    'Baran',
    'Barmer',
    'Barpeta',
    'Barwani',
    'Bastar',
    'Bathery',
    'Belgaum',
    'Bellary',
    'Bemetara',
    'Bengaluru',
    'Berhampore',
    'Betul',
    'Bhadradri Kothagudem',
    'Bharananganam',
    'Bharanikkavu',
    'Bharatpur',
    'Bhavnagar',
    'Bhayander',
    'Bhilwara',
    'Bhind',
    'Bhopal',
    'Bhubaneswar',
    'Bhupalpally',
    'Bidar',
    'Bihar Sharif',
    'Bikaner',
    'Bilaspur',
    'Biswanath',
    'Bokaro',
    'Bongaigaon',
    'Boudh',
    'Budhanoor',
    'Bulandshahar',
    'Bundi',
    'Burhanpur',
    'Bysonvalley',
    'Cachar',
    'Chadayamangalam',
    'Chakkittappara',
    'Chakkupallam',
    'Chalakudy',
    'Chalisserri',
    'Chaliyar',
    'Champakulam',
    'Chandigarh',
    'Changanacherry',
    'Changaroth',
    'Chapparapadavu',
    'Charaideo',
    'Chathamangalam',
    'Chathannur',
    'Chavakkad',
    'Chavara',
    'Chazhoor',
    'Cheekode',
    'Chekkyad',
    'Chelannur',
    'Chelembra',
    'Chellanam',
    'Chembilode',
    'Chemencherry',
    'Chemmaruthi',
    'Chendamangalam',
    'Chengalai',
    'Chengalpattu',
    'Chengamanade',
    'Chengannur',
    'Chengottukavu',
    'Chenkal',
    'Chennai',
    'Chennam Pallippuram',
    'Chennerkara',
    'Chennithala',
    'Cheppad',
    'Cheranalloor',
    'Cheriyamundam',
    'Cheriyanad',
    'Cherppalasseri',
    'Cherpu',
    'Cherthala',
    'Cherukavu',
    'Cherukol',
    'Cherukunnu',
    'Cherunniyoor',
    'Cherupuzha',
    'Cheruthana',
    'Cheruthazham',
    'Cheruvannur',
    'Chettikulangara',
    'Chhatarpur',
    'Chheharta',
    'Chhindwara',
    'Chingoli',
    'Chinnakanal',
    'Chirakkadavu',
    'Chirakkal',
    'Chirakkara',
    'Chirang',
    'Chirayinkeezhu',
    'Chithara',
    'Chittar',
    'Chittariparamb',
    'Chittattukara',
    'Chittorgarh',
    'Chittur ULB',
    'Chogawan',
    'Chokkad',
    'Chokli',
    'Choondal',
    'Choornikkara',
    'Chorode',
    'Chowannur',
    'Chunakkara',
    'Chungathara',
    'Churu',
    'Clappana',
    'Coimbatore',
    'Cuddalore',
    'Cuttack',
    'Cyberabad',
    'Damoh',
    'Dantewada',
    'Darbhanga',
    'Darrang',
    'Datia',
    'Dausa',
    'Dehradun',
    'Delhi',
    'Deoghar',
    'Desamangalam',
    'Devikulam',
    'Devikulangara',
    'Dewas',
    'Dhamtari',
    'Dhanbad',
    'Dhankheti',
    'Dhar',
    'Dharmadam',
    'Dharmapuri',
    'Dhemaji',
    'Dholpur',
    'Dhubri',
    'Dhule',
    'Dibrugarh',
    'Dima Hasao',
    'Dindori',
    'Dindugul',
    'Dungarpur',
    'East Garo Hills',
    'East Jaintia Hills',
    'Edachery',
    'Edakkara',
    'Edakkattuvayal',
    'Edamulakkal',
    'Edapatta',
    'Edappal',
    'Edarikode',
    'Edathala',
    'Edathiruthi',
    'Edathua',
    'Edavaka',
    'Edavanakkad',
    'Edavanna',
    'Edavetty',
    'Edavilangu',
    'Edayur',
    'Elakamon',
    'Elamadu',
    'Elamkulam',
    'Elamkunnapuzh.',
    'Elampalloor',
    'Elanji',
    'Elanthoor',
    'Elappara',
    'Elapully',
    'Elavally',
    'Elavanchery',
    'Elikulam',
    'Eloor',
    'Enadimangalam',
    'Engandiyoor',
    'Eramala',
    'Eramam',
    'Eranjoli',
    'Erath',
    'Erattupetta',
    'Eraviperoor',
    'Erimayur',
    'Eriyad',
    'Erode',
    'Eroor',
    'Erumely',
    'Eruthenpathy',
    'Eruvessi',
    'Ettumanoor',
    'Ezhamkulam',
    'Ezhikkara',
    'Ezhome',
    'Ezhukone',
    'Ezhumattoor',
    'Ezhupunna',
    'Faridabad',
    'Faridkot',
    'Feroke',
    'Gadwal',
    'Ganganagar',
    'Gangtok',
    'Ghaziabad',
    'Goalpara',
    'Golaghat',
    'Goniana',
    'Gorakhpur',
    'Grp Ajmer',
    'Grp Jodhpur',
    'Gulbarga',
    'Guna',
    'Gurgaon',
    'Guruvayur',
    'Guwahati',
    'Guwahati City',
    'Gwalior',
    'Hailakandi',
    'Haldwani',
    'Hamirpur',
    'Hamren',
    'Hanumangarh',
    'Harda',
    'Haripad',
    'Hassan',
    'Hazaribagh',
    'Hojai',
    'Hoshangabad',
    'Hoshiarpur',
    'Howrah',
    'Hubli–Dharwad',
    'Hyderabad',
    'Imphal',
    'Indore',
    'Irikkur',
    'Irimbiliyam',
    'Irinjalakkuda',
    'Iritty',
    'Ittiva',
    'Jabalpur',
    'Jagdalpur',
    'Jagtial',
    'Jaipur',
    'Jaipur Rural',
    'Jaisalmer',
    'Jalna',
    'Jalore',
    'Jammu',
    'Jamnagar',
    'Jamshedpur',
    'Janagoan',
    'Jandiala Guru',
    'Jangaon',
    'Janjgir',
    'Jayashankar Bhupalapally',
    'Jehanabad',
    'Jhabua',
    'Jhalawar',
    'Jhunjhunu',
    'Jhunjhunuu',
    'Jodhpur',
    'Jodhpur Rural',
    'Jogulamba Gadwal',
    'Jorhat',
    'Jowai',
    'Kabirdham',
    'Kadakkal',
    'Kadakkarapally',
    'Kadakkavoor',
    'Kadalundi',
    'Kadamakkudy',
    'Kadamakudy',
    'Kadambazhippuram',
    'Kadambur',
    'Kadampanad',
    'Kadanadu',
    'Kadangod',
    'Kadannapalli',
    'Kadapa',
    'Kadaplamattom',
    'Kadapra',
    'Kadavallur',
    'Kadinamkulam',
    'Kadukutty',
    'Kaduthuruthy',
    'Kainakary',
    'Kaiparambu',
    'Kaippamangalam',
    'Kakinada',
    'Kakkodi',
    'Kakkur',
    'Kaladi',
    'Kalady',
    'Kalamassery',
    'Kalanjoor',
    'Kalikavu',
    'Kallakurichi',
    'Kallara',
    'Kalliassery',
    'Kallikkadu',
    'Kalloopara',
    'Kalloorkkad',
    'Kalluvathukkal',
    'Kalpakanchery',
    'Kalpetta',
    'Kalyan-Dombivli',
    'Kamareddy',
    'Kamrup',
    'Kanakkary',
    'Kancheepuram',
    'Kanchiyar',
    'Kandalloor',
    'Kandanassery',
    'Kangazha',
    'Kangra',
    'Kanichar',
    'Kaniyambetta',
    'Kanjikuzhi',
    'Kanjiramkulam',
    'Kanjirappally',
    'Kanjirappuzha',
    'Kanjoor',
    'Kannadi',
    'Kannamangalam',
    'Kannambra',
    'Kannapuram',
    'Kannur',
    'Kanthaloor',
    'Kanyakumari',
    'Kappur',
    'Karakurissi',
    'Karalam',
    'Karassery',
    'Karauli',
    'Karavaloor',
    'Karavaram',
    'Karbi Anglong',
    'Kareepra',
    'Karimannoor',
    'Karimba',
    'Karimganj',
    'Karimnagar',
    'Karimpuzha',
    'Karinkunnam',
    'Karivellur Peralam',
    'Karode',
    'Karoor',
    'Karthikapally',
    'Karukachal',
    'Karulai',
    'Karumalloor',
    'Karumkulam',
    'Karunagappally',
    'Karunapuram',
    'Karur',
    'Karuvarakund',
    'Karuvatta',
    'Kasaragod',
    'Katghora',
    'Kathirur',
    'Katni',
    'Kattakambal',
    'Kattappana Municipality',
    'Kattippara',
    'Kattoor',
    'Kavalam',
    'Kavalangad',
    'Kavanur',
    'Kavasserri',
    'Kavilumpara',
    'Kaviyoor',
    'Kayakkodi',
    'Kayamkulam',
    'Kayanna',
    'Keerampara',
    'Keezhallur',
    'Keezhariyur',
    'Keezhattur',
    'Keezhmad',
    'Keezhuparamba',
    'Kelakam',
    'Keralasseri',
    'Khammam',
    'Khandwa',
    'Kharar',
    'Khargone',
    'Khliehriat',
    'Khunti',
    'Kidangoor',
    'Kizhakkekallada',
    'Kizhakoth',
    'Kizhekkencheri',
    'Kizhuvilam',
    'Kochi',
    'Kodakara',
    'Kodamthuruth',
    'Kodassery',
    'Kodenchery',
    'Kodumbu',
    'Kodumon',
    'Kodungallur',
    'Kodur',
    'Koduvally',
    'Koduvayur',
    'Kokkyar',
    'Kokrajhar',
    'Kolachery',
    'Kolayad',
    'Kolkata',
    'Kollam',
    'Kollam East',
    'Kollayil',
    'Kollemkode',
    'Kondazhy',
    'Kondotty',
    'Kongad',
    'Konnathadi',
    'Konni',
    'Koodaranhi',
    'Koorachundu',
    'Kooroppada',
    'Koothali',
    'Koothattukulam',
    'Koothuparamba',
    'Koottickal',
    'Koottilangadi',
    'Koovappady',
    'Koppam',
    'Koratty',
    'Korba',
    'Korea',
    'Koruthodu',
    'Kota',
    'Kota City',
    'Kota Rural',
    'Kothagudem',
    'Kothamangalam',
    'Kottakkal',
    'Kottamkara',
    'Kottangal',
    'Kottarakkara',
    'Kottathara',
    'Kottayam',
    'Kottayi',
    'Kottiyoor',
    'Kottnadu',
    'Kottoppadam',
    'Kottukal',
    'Kottur',
    'Kottuvally',
    'Koyilandy',
    'Koyipuram',
    'Kozhencherry',
    'Kozhikode',
    'Kozhinjampara',
    'Kozhuvanal',
    'Krishnagiri',
    'Krishnapuram',
    'Kudayathoor',
    'Kulakkada',
    'Kulanada',
    'Kulasekharapuram',
    'Kulathoor',
    'Kulathupuzha',
    'Kulukkallur',
    'Kumaly',
    'Kumarakom',
    'Kumaramangalam',
    'Kumarampathur',
    'Kumarapuram',
    'Kumbalam',
    'Kumbalangy',
    'Kummil',
    'Kumuram Bheem Asifabad',
    'Kundara',
    'Kunjimanagalam',
    'Kunnamangalam',
    'Kunnamkulam',
    'Kunnamthanam',
    'Kunnathoor',
    'Kunnathukal',
    'Kunnathunad',
    'Kunnothuparambu',
    'Kunnukara',
    'Kunnummel',
    'Kuravilangadu',
    'Kurichy',
    'Kurnool',
    'Kurumathoor',
    'Kuruva',
    'Kuruvattoor',
    'Kuthanur',
    'Kuthiyathode',
    'Kuttampuzha',
    'Kuttichal',
    'Kuttippuram',
    'Kuttiyatoor',
    'Kuttor',
    'Kuttyadi',
    'Kuzhalmannam',
    'Kuzhimanna',
    'Kuzhuppily',
    'Lakhimpur',
    'Latur',
    'Lekkidi Peroor',
    'Lopoke',
    'Lucknow',
    'Ludhiana',
    'M G Kavu',
    'MUZHAKKUNNU',
    'Maangattidam',
    'Madappally',
    'Madavoor',
    'Madayi',
    'Madurai',
    'Mahabubabad',
    'Mahabubnagar',
    'Mahasamund',
    'Mahbubnagar',
    'Mairang',
    'Majitha',
    'Majuli',
    'Makkaraparamu',
    'Mala',
    'Malampuzha',
    'Malapattam',
    'Malappuram',
    'Malayalppuzha',
    'Malayattoor',
    'Malayinkeezhu',
    'Mallappally',
    'Mallappuzhassery',
    'Maloor',
    'Mampad',
    'Manakkadu',
    'Manaloor',
    'Manamboor',
    'Mananthavadi',
    'Mananthavady',
    'Manarkadu',
    'Manawala',
    'Mancherial',
    'Mandla',
    'Mandsaur',
    'Maneed',
    'Mangalam',
    'Mangalapuram',
    'Mangalore',
    'Manickal',
    'Manimala',
    'Maniyur',
    'Manjallur',
    'Manjapra',
    'Manjeri',
    'Manjoor',
    'Mankada',
    'Mankara',
    'Mankulam',
    'Mannacherry',
    'Mannar',
    'Mannarkkad',
    'Mannnchery',
    'Mannur',
    'Maradu',
    'Marakkara',
    'Maranchery',
    'Marangattupally',
    'Mararikkulam',
    'Mararikulam',
    'Maravanthuruthu',
    'Marayoor',
    'Mariang',
    'Mariyapuram',
    'Marutharoad',
    'Maruthonkara',
    'Mathilakam',
    'Mathur',
    'Matool',
    'Mattanur',
    'Mattathoor',
    'Mavelikkara ULB',
    'Mavoor',
    'Mawkyrwat',
    'Mayyanad',
    'Mayyil',
    'Medak',
    'Medchal',
    'Medchal Malkajgiri',
    'Meenachil',
    'Meenadam',
    'Meenanagadi',
    'Meerut',
    'Melarkodu',
    'Melattur',
    'Melila',
    'Meloor',
    'Melukavu',
    'Mepayyur',
    'Meppadi',
    'Mezhuveli',
    'Midnapore',
    'Mira Road',
    'Miraj',
    'Mohali (SAS Nagar)',
    'Mokeri',
    'Moodady',
    'Mookkannoor',
    'Moonnilavu',
    'Moopainad',
    'Moopainadu',
    'Moorkanad',
    'Moothedam',
    'Morayur',
    'Morbi',
    'Morena',
    'Morigaon',
    'Mudakkal',
    'Mudakkuzha',
    'Muhamma',
    'Mukkam',
    'Mulakkuzha',
    'Mulakulam',
    'Mulanthuruthy',
    'Mulavukad',
    'Mullassery',
    'Mullenkolly',
    'Mullurkkara',
    'Mulugu',
    'Mumbai',
    'Mundakkayam',
    'Munderi',
    'Mundoor',
    'Mundrothuruthu',
    'Mungeli',
    'Munnar',
    'Munniyur',
    'Muriyad',
    'Muthalamada',
    'Muthuthala',
    'Muthuvallur',
    'Muttar',
    'Muttil',
    'Muttom',
    'Muzhappilangad',
    'Muzzafarpur',
    'Mylapara',
    'Mylom',
    'Mynagappally',
    'Mysore',
    'Nadapuram',
    'Nadathara',
    'Naduvannur',
    'Naduvil',
    'Nagalasserri',
    'Nagaon',
    'Nagapattinam',
    'Nagarkurnool',
    'Nagaur',
    'Nagercoil',
    'Nagpur',
    'Nalbari',
    'Nalgonda',
    'Namakkal',
    'Nandurbar',
    'Nanminda',
    'Nannambra',
    'Nannamukku',
    'Nanniyode',
    'Naranammoozhi',
    'Naranganam',
    'Narath',
    'Narayanpet',
    'Naraynpur',
    'Narikunni',
    'Naripetta',
    'Narsinghpur',
    'Nashik',
    'Nasik City',
    'Nathdwara',
    'Nattika',
    'Navaikulam',
    'Navi Mumbai',
    'Nayarambalam',
    'Nedumbassery',
    'Nedumkandom',
    'Nedumkunnam',
    'Nedumpana',
    'Nedumpram',
    'Nedumudy',
    'Neduvathoor',
    'Neelamperoor',
    'Neemuch',
    'Neendakara',
    'Neendoor',
    'Nellaya',
    'Nelliampathy',
    'Nemmara',
    'Nenmanikkara',
    'Nenmeni',
    'New Amritsar',
    'New Delhi',
    'New mahi',
    'Neyyattinkara Cds',
    'Nilambur',
    'Nilamel',
    'Niramaruthur',
    'Niranam',
    'Nirmal',
    'Niwari',
    'Nizamabad',
    'Njarakka',
    'Njeezhoor',
    'Nochad',
    'Noida',
    'Nongpoh',
    'Nongstoin',
    'Noolpuzha',
    'Nooranad',
    'North Garo Hills',
    'Oachira',
    'Okkal',
    'Olavanna',
    'Omallor',
    'Omasseri',
    'Onchium',
    'Ongallur',
    'Oorakam',
    'Oorngattiri',
    'Orumanyoor',
    'Othukungal',
    'Ottappalam',
    'Ottasekharamangalam',
    'Ozhur',
    'PAN State',
    'PERAVOOR',
    'Paatyam',
    'Padinjarathra',
    'Padiyoor',
    'Padyoor',
    'Paingottoor',
    'Paippadu',
    'Paipra',
    'Pakur',
    'Pala',
    'Palakkad ulb',
    'Palamel',
    'Palghar',
    'Pali',
    'Pallarimangalam',
    'Pallassana',
    'Pallickal',
    'Pallickathodu',
    'Pallikkal',
    'Pallippad',
    'Pallipuram',
    'Pallivasal',
    'Pampady',
    'Pampakkuda',
    'Panachikadu',
    'Panaji',
    'Pananchery',
    'Panangad',
    'Panavally - ruchi',
    'Panayam',
    'Pandalam Municipality',
    'Pandalam Thekkekara',
    'Pandikkad',
    'Panjal',
    'Panmana',
    'Panna',
    'Pannyannur',
    'Panoor',
    'Pappinisseri',
    'Parakkadavu',
    'Parapookkara',
    'Parappananagadi',
    'Parappur',
    'Parassala',
    'Parathodu',
    'Paravoor',
    'Parbhani',
    'Pariyaram',
    'Parli',
    'Paruthur',
    'Pathanamthitta',
    'Pathanapuram',
    'Pathankot',
    'Pathiyoor',
    'Patiala',
    'Patna',
    'Pattambi',
    'Pattanakkad',
    'Pattazhi',
    'Pattazhi North',
    'Pattencherry',
    'Pattithara',
    'Pattuvam',
    'Pavaratty',
    'Pavithreswaram',
    'Payyanur',
    'Payyavoor',
    'Payyoli',
    'Pazhayakunnumel',
    'Pazhayannur',
    'Peddapalli',
    'Peddapally',
    'Peermade',
    'Peralassery',
    'Perambalur',
    'Perambra',
    'Perayam',
    'Perinad',
    'Peringara',
    'Peringom Vayakkara',
    'Peringottukkurrissi',
    'Perinjanam',
    'Perinthalmanna',
    'Perumanna',
    'Perumanna Klari',
    'Perumatti',
    'Perumbalam',
    'Perumbavoor',
    'Perumkadavila',
    'Perumpadappu',
    'Perunad',
    'Peruvallur',
    'Peruvayal',
    'Peruvemba',
    'Pimpri Chinchwad',
    'Pinarayi',
    'Pindimana',
    'Piravam',
    'Piravanthoor',
    'Pirayiri',
    'Polpully',
    'Ponmala',
    'Ponmudam',
    'Ponnani',
    'Pookkottukavu',
    'Pookkottur',
    'Poomangalam',
    'Poonjar',
    'Poonjar Thekkekkara',
    'Poothadi',
    'Poothakkulam',
    'Pootrikka',
    'Poovar',
    'Pooyappally',
    'Porkulam',
    'Port Blair',
    'Porur',
    'Poruvazhy',
    'Pothanikkad',
    'Pothencode',
    'Pothukal',
    'Pozhuthana',
    'Pramadam',
    'Pratapgarh',
    'Puducherry',
    'Pudukkad',
    'Pudukottai',
    'Pulamanthole',
    'Pulikkal',
    'Pulimath',
    'Pulincunnu',
    'Pulpatta',
    'Punalur',
    'Pune',
    'Punnappara North',
    'Punnapra South',
    'Punnayoor',
    'Punnayoorkulam',
    'Puramattom',
    'Purameri',
    'Purappuzha',
    'Purathur',
    'Puthanvelikkara',
    'Puthenchira',
    'Puthukodu',
    'Puthunagaram',
    'Puthupally',
    'Puthupariyaram',
    'Puthuppadi',
    'Puthur',
    'Puthusseri',
    'Puzhakkattiri',
    'Raigarh',
    'Raipur',
    'Raisen',
    'Rajakkadu',
    'Rajakumari',
    'Rajanna Sircilla',
    'Rajanna Siricilla',
    'Rajasansi',
    'Rajgarh',
    'Rajkot',
    'Rajnandgaon',
    'Rajsamand',
    'Ramamangalam',
    'Ramanathapuram',
    'Ramanattukara',
    'Ramankary',
    'Ramanthalli',
    'Ramapuram',
    'Ranchi',
    'Ranga Reddy',
    'Ranga reddy',
    'Rangareddy',
    'Ranipet',
    'Ranni',
    'Ranni Angadi',
    'Ranni Pazhavangadi',
    'Ratlam',
    'Rayamangalam',
    'Rayya',
    'Rewa',
    'Rishikesh',
    'Rohtak',
    'S N Puram',
    'Sadiya',
    'Sagar',
    'Sahibganj',
    'Saifai',
    'Salem',
    'Sangareddy',
    'Sangli',
    'Santhenpara',
    'Sasthamcotta',
    'Satna',
    'Sawai Madhopur',
    'Secunderabad',
    'Seethathode',
    'Sehore',
    'Senapathy',
    'Seoni',
    'Shahdol',
    'Shajapur',
    'Sheopur',
    'Shillong',
    'Shimla',
    'Shimoga',
    'Shivpuri',
    'Sholaur',
    'Sholayur',
    'Shoranur',
    'Siddipet',
    'Sidhi',
    'Sikar',
    'Silchar',
    'Siliguri',
    'Singrauli',
    'Sirohi',
    'Sivaganga',
    'Sivasagar',
    'Solapur',
    'Sonepat',
    'Sonitpur',
    'Sooranadu North',
    'Sooranadu South',
    'South Garo Hills',
    'South Salmara',
    'South West Garo Hills',
    'Sreekandapuram',
    'Sreekrishnapuram',
    'Sreemoola nagaram',
    'Sri Ganganagar',
    'Sriganganagar',
    'Srinagar',
    'Sukma',
    'Surajpur',
    'Surat',
    'Suryapet',
    'T.V. Puram',
    'THRIPUNITHURA',
    'Tanur',
    'Tavanur',
    'Tenkasi',
    'Tezpur',
    'Thachampara',
    'Thachanattukara',
    'Thakazhi',
    'Thalakkad',
    'Thalakkulathur',
    'Thalanadu',
    'Thalappalam',
    'Thalassery',
    'Thalavady',
    'Thalavoor',
    'Thalayazham',
    'Thalayolaparambu',
    'Thaliparamba',
    'Thamarakkulam',
    'Thamarassery',
    'Thanalur',
    'Thane',
    'Thanjavur',
    'Thanneermukkom',
    'Thanniam',
    'Thannithode',
    'Thariode',
    'Tharur',
    'Thavinjal',
    'Thazhakkara',
    'Thazhava',
    'Thazhekode',
    'The Nilgiris',
    'Theekoy',
    'Thekkekkara',
    'Thekkumbhagom',
    'Thekkumkara',
    'Thenhipalam',
    'Theni',
    'Thenkara',
    'Thenkkurrussi',
    'Thenmala',
    'Thevalakkara',
    'Thidanadu',
    'Thikkodi',
    'Thillenkeri',
    'Thirumarady',
    'Thirumittakode',
    'Thirunelly',
    'Thirupuram',
    'Thiruvali',
    'Thiruvalla East',
    'Thiruvalla West',
    'Thiruvallur',
    'Thiruvambady',
    'Thiruvananthapuram',
    'Thiruvaniyoor',
    'Thiruvankulam',
    'Thiruvarppu',
    'Thiruvarur',
    'Thiruvegappura',
    'Thiruvilwamala',
    'Thodiyoor',
    'Thodupuzha municipality',
    'Thollur',
    'Thondernadu',
    'Thoothukudi',
    'Thottappuzhassery',
    'Thrikkadeeri',
    'Thrikkakara East',
    'Thrikkakara West',
    'Thrikkalangode',
    'Thrikkaruva',
    'Thrikkodithanam',
    'Thrikkovilvattom',
    'Thrikkunnapuzha',
    'Thrikoor',
    'Thriprangode',
    'Thrissur',
    'Thriunavaya',
    'Thumpamon',
    'Thuravoor',
    'Thuravur',
    'Thurayur',
    'Thuvvur',
    'Thycattussery',
    'Tikamgarh',
    'Tinsukia',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tirupati',
    'Tirupattur',
    'Tiruppur',
    'Tirur',
    'Tirurangadi',
    'Tiruvallur',
    'Tiruvannamalai',
    'Tiruvarur',
    'Tonk',
    'Trichy',
    'Triprangottur',
    'Trithala',
    'Tumkur',
    'Tuneri',
    'Tura',
    'Udaipur',
    'Udalguri',
    'Udayagiri',
    'Udayanapuram',
    'Udgir',
    'Udhampur',
    'Udhayamperoor',
    'Udupi',
    'Ujjain',
    'Ulikkal',
    'Ulliyeri',
    'Umaria',
    'Ummannur',
    'Unnnikulam',
    'Upputhara',
    'Uzhamalaykkal',
    'Uzhavoor',
    'Vadakara',
    'Vadakarapathy',
    'Vadakkekkad',
    'Vadakkekkara',
    'Vadakkenchery',
    'Vadanappilly',
    'Vadasserikara',
    'Vadavannur',
    'Vadavukode Puthancruz',
    'Vadodara',
    'Vaikom',
    'Vakathanam',
    'Vakkom',
    'Valakom',
    'Valanchery',
    'Valapattanam',
    'Valappad',
    'Valavannur',
    'Valayam',
    'Vallachira',
    'Vallapuzha',
    'Vallatholenagar',
    'Vallickode',
    'Vallikunnam',
    'Vallikunnu',
    'Vandanmedu',
    'Vandazhi',
    'Vandiperiyar',
    'Vanimel',
    'Vaniyamkulam',
    'Vannapuram',
    'Varanasi',
    'Varantharappilly',
    'Varapuzha',
    'Varavoor',
    'Varkkala',
    'Vathikudy',
    'Vattamkulam',
    'Vattavada',
    'Vayalar',
    'Vazhakkad',
    'Vazhakulam',
    'Vazhappally',
    'Vazhathope',
    'Vazhayur',
    'Vazhikkadavu',
    'Vazhoor',
    'Vechoochira',
    'Vechoor',
    'Veeyapuram',
    'Velinallur',
    'Veliyam',
    'Veliyamcode',
    'Veliyanad',
    'Veliyannoor',
    'Vellamunda',
    'Vellanad',
    'Vellangallur',
    'Vellarada',
    'Vellathooval',
    'Vellavoor',
    'Vellinezhi',
    'Velliyamattam',
    'Velloor',
    'Vellore',
    'Velom',
    'Velookkara',
    'Veloor',
    'Vengad',
    'Venganoor',
    'Vengapally',
    'Vengara',
    'Vengola',
    'Vengoor',
    'Venkitangu',
    'Venmony',
    'Verka',
    'Vettathur',
    'Vettikkavala',
    'Vettom',
    'Vettor',
    'Vidisha',
    'Vijayapuram',
    'Vijayawada',
    'Vikarabad',
    'Vilakkudy',
    'Vilappil',
    'Vilayur',
    'Villupuram',
    'Villyappalli',
    'Virudhunagar',
    'Visakhapatnam',
    'Vithura',
    'Vythiri',
    'Wadakkanchery',
    'Wanaparthy',
    'Wandoor',
    'Warangal',
    'Warangal Rural',
    'Warangal Urban',
    'Warangal Urban & Rural',
    'Wardha',
    'Wayanad',
    'West Garo Hills',
    'West Kallada',
    'West Singhbhum',
    'Williamnagar',
    'Yadadri Bhongiri',
    'Yadadri Bhuvanagiri',
    'chalavara',
    'irinjalakuda block panchayath',
    'jashpur nagar',
    'kalpetta',
    'kothamangalam',
    'kunnathunadu',
    'nallepilly',
    'ottapalam',
    'panamaram',
    'pandanad',
    'pariyaram',
    'payam',
    'puliyoor',
    'pulpally',
    'purakkad',
    'shoranur',
    'thiruvanvandoor'
  ];

  @override
  Widget build(BuildContext context) {
//    final halfMediaWidth = MediaQuery.of(context).size.width / 2.0;

    void _toDash() {
      Navigator.of(context).popUntil((route) => route.isFirst);
    }

    return WillPopScope(
        onWillPop: () {
          _toDash();
        },
        child: Scaffold(
          backgroundColor: Colors.white,

//      key: _formKey,
          appBar: AppBar(
            leading: IconButton(
                icon: Icon(Icons.arrow_back, color: Colors.black),
                // onPressed: () => Navigator.push(
                //   context,
                //   PageTransition(
                //       type: PageTransitionType.rightToLeft,
                //       duration: Duration(milliseconds: 600),
                //       child: Dash()),
                // ),
                onPressed: () {
                  Navigator.of(context).popUntil((route) => route.isFirst);
                }),
            backgroundColor: Colors.white,
            iconTheme: new IconThemeData(color: Colors.black),
            title: Padding(
              padding: const EdgeInsets.only(top: 5.0),
              child: Text(
                "Choose Your City",
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 20.0,
                ),
              ),
            ),
            elevation: 0,
          ),
          resizeToAvoidBottomInset: false,
          body: Container(
              padding: EdgeInsets.all(15.0),
              child: SingleChildScrollView(
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisSize: MainAxisSize.max,
                    children: <Widget>[
                      Padding(
                        padding: const EdgeInsets.only(top: 20),
                        child: DropDownField(
                          onValueChanged: (dynamic value) {
                            city_id = value;
                          },
                          value: city_id,
                          required: false,
                          hintText: 'Type in your city',
                          labelText: 'City',
                          labelStyle: TextStyle(color: Colors.black),
                          items: city,
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.only(top: 20, right: 250),
                        child: RaisedButton(
                          color: Colors.white,
                          elevation: 7,
                          child: Text(
                            "Next",
                            style: TextStyle(color: Colors.blue[900]),
                          ),
                          onPressed: () {
                            checkAndPass();
                          },
                        ),
                      )
                    ]),
              )),
        ));
  }

  void checkAndPass() {
    if (city_id != null) {
      Navigator.pushReplacement(
          context,
          MaterialPageRoute(
              builder: (context) => SelectResources(
                    city: city_id,
                  )));
    } else {
      _showDialog();
    }
  }

  void _showDialog() {
    showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: new Text("Select City"),
            content: new Text("Please select your city to proceed"),
            actions: <Widget>[
              FlatButton(
                child: new Text("OK"),
                onPressed: () {
                  Navigator.pushReplacement(
                      context, MaterialPageRoute(builder: (context) => App()));
                },
              ),
            ],
          );
        });
  }
}
